### ISSUE TITLE
transform error in produce_dem

### ISSUE THREAD

**Issue by davidfee5** [uafgeotools/rtm#43]
I'm now getting an error on an unsupported transform in produce_dem. Looks like cartopy is unhappy. 

"Generating DEM hillshade plot...
Traceback (most recent call last):

  File "<ipython-input-10-a7dbf5bbbb8f>", line 4, in <module>
    search_dem = produce_dem(search_grid, external_file=EXTERNAL_FILE, plot_output=True)

  File "/Users/dfee/repos/rtm/rtm/grid.py", line 365, in produce_dem
    ax.scatter(*dem.grid_center, s=50, color='limegreen',

  File "/Users/dfee/anaconda/envs/rtm/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 305, in wrapper
    raise ValueError('Invalid transform: Spherical {} '

ValueError: Invalid transform: Spherical scatter is not supported - consider using PlateCarree/RotatedPole."

**Comment by liamtoney** [comment]
I think this can be fixed by replacing `ccrs.Geodetic()` with`ccrs.PlateCarree()` in [the offending line](https://github.com/uafgeotools/rtm/blob/3afe442c476dc59be62db3a7db92ee50180b8f60/rtm/grid.py#L365). See: https://stackoverflow.com/questions/13657748/contouring-with-cartopy-valueerror-invalid-transform-spherical-contouring-is

**Comment by davidfee5** [comment]
Yep, that was easy! I'll create a pull request.
